#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get update
sudo apt-get install -y haproxy

sudo chown -R $USER /etc/haproxy
sudo chown -R $USER /etc/default/haproxy

printf %s "
frontend hbnb-lb_front
        bind *:80
        mode http
        default_backend hbnb-lb_back
backend hbnb-lb_back
        balance roundrobin
        server 158041-web-01 b.yandev.tech:80 check
        server 158041-web-02 18.206.207.55:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy start
