#!/usr/bin/env bash
# FizzBuzz

num=1
while [ "$num" -lt 101  ]
do
	if [ $(("$num"%3)) -eq 0 ] && [ $(("$num"%5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $(("$num"%3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $(("$num"%5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$num"
	fi
	num=$(("$num"+1))
done
